# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import asr_pb2 as asr__pb2


class AsrStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamingRecognize = channel.stream_stream(
                '/voicera.asr.v1.Asr/StreamingRecognize',
                request_serializer=asr__pb2.StreamingRequest.SerializeToString,
                response_deserializer=asr__pb2.StreamingResponse.FromString,
                )
        self.Recognize = channel.unary_unary(
                '/voicera.asr.v1.Asr/Recognize',
                request_serializer=asr__pb2.RecognizeRequest.SerializeToString,
                response_deserializer=asr__pb2.RecognizeResponse.FromString,
                )


class AsrServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamingRecognize(self, request_iterator, context):
        """Live audio. The first message MUST be a config; every message after it is
        audio. Transcripts stream back as they form. Half-close to finish the turn.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Recognize(self, request, context):
        """Whole-file, for parity with POST /v1/audio/transcriptions.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AsrServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamingRecognize': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamingRecognize,
                    request_deserializer=asr__pb2.StreamingRequest.FromString,
                    response_serializer=asr__pb2.StreamingResponse.SerializeToString,
            ),
            'Recognize': grpc.unary_unary_rpc_method_handler(
                    servicer.Recognize,
                    request_deserializer=asr__pb2.RecognizeRequest.FromString,
                    response_serializer=asr__pb2.RecognizeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'voicera.asr.v1.Asr', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Asr(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamingRecognize(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/voicera.asr.v1.Asr/StreamingRecognize',
            asr__pb2.StreamingRequest.SerializeToString,
            asr__pb2.StreamingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Recognize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/voicera.asr.v1.Asr/Recognize',
            asr__pb2.RecognizeRequest.SerializeToString,
            asr__pb2.RecognizeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
