# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from . import tts_pb2 as tts__pb2


class TTSServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Synthesize = channel.unary_stream(
            "/tts.TTSService/Synthesize",
            request_serializer=tts__pb2.SynthesizeRequest.SerializeToString,
            response_deserializer=tts__pb2.SynthesizeResponse.FromString,
        )


class TTSServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Synthesize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_TTSServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Synthesize": grpc.unary_stream_rpc_method_handler(
            servicer.Synthesize,
            request_deserializer=tts__pb2.SynthesizeRequest.FromString,
            response_serializer=tts__pb2.SynthesizeResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "tts.TTSService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


class TTSService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Synthesize(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/tts.TTSService/Synthesize",
            tts__pb2.SynthesizeRequest.SerializeToString,
            tts__pb2.SynthesizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
