# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tts.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ttts.proto\x12\x03tts\"J\n\x11SynthesizeRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x10\n\x08language\x18\x03 \x01(\t\"\x81\x01\n\x12SynthesizeResponse\x12\x1e\n\x04meta\x18\x01 \x01(\x0b\x32\x0e.tts.MetaFrameH\x00\x12 \n\x05\x61udio\x18\x02 \x01(\x0b\x32\x0f.tts.AudioChunkH\x00\x12\x1e\n\x04\x64one\x18\x03 \x01(\x0b\x32\x0e.tts.DoneFrameH\x00\x42\t\n\x07payload\"N\n\tMetaFrame\x12\x0b\n\x03pid\x18\x01 \x01(\t\x12\x13\n\x0bsample_rate\x18\x02 \x01(\x05\x12\r\n\x05\x64type\x18\x03 \x01(\t\x12\x10\n\x08\x63hannels\x18\x04 \x01(\x05\"\x1e\n\nAudioChunk\x12\x10\n\x08pcm_data\x18\x01 \x01(\x0c\"\x18\n\tDoneFrame\x12\x0b\n\x03pid\x18\x01 \x01(\t2M\n\nTTSService\x12?\n\nSynthesize\x12\x16.tts.SynthesizeRequest\x1a\x17.tts.SynthesizeResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tts_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SYNTHESIZEREQUEST']._serialized_start=18
  _globals['_SYNTHESIZEREQUEST']._serialized_end=92
  _globals['_SYNTHESIZERESPONSE']._serialized_start=95
  _globals['_SYNTHESIZERESPONSE']._serialized_end=224
  _globals['_METAFRAME']._serialized_start=226
  _globals['_METAFRAME']._serialized_end=304
  _globals['_AUDIOCHUNK']._serialized_start=306
  _globals['_AUDIOCHUNK']._serialized_end=336
  _globals['_DONEFRAME']._serialized_start=338
  _globals['_DONEFRAME']._serialized_end=362
  _globals['_TTSSERVICE']._serialized_start=364
  _globals['_TTSSERVICE']._serialized_end=441
# @@protoc_insertion_point(module_scope)